
spring.application.name=parkingFlow
server.port=8082


spring.datasource.url=jdbc:postgresql://localhost:5432/parkingflow
spring.datasource.username=postgres
spring.datasource.password=Pancito11ProMax...
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita el aviso amarillo de Open-In-View
spring.jpa.open-in-view=false


# Si algo falla en la creación, esto te dirá EXACTAMENTE qué fue
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.tool.schema=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT 
jwt.secret=f6dba95a88d2c100b4647194c35df7475b7b3a487631ac5b40ae015a71962517
jwt.expiration=3600000
jwt.refresh-expiration=86400000

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none