spring.application.name=parkingFlow

server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/parkingflow
spring.datasource.username=postgres
spring.datasource.password=x121212x.Mazo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect